Fix for the three space indent on using-shared-components branch.
arunoda/learnnextjs-demo pull request #54
Opened 2019-02-09 23:49 UTC by andersonleite

Fix for the three space indent on using-shared-components branch.

2019-02-12 00:38 UTC, lucleray requested changes

2019-02-12 00:38 UTC, lucleray commented on package.json
> +    "next": "^7.0.2",
We can update next to 8.0.0 now that it's out 🙂

2019-02-12 00:38 UTC, lucleray commented on package.json
> +    "react-dom": "^16.7.0"
We can update this to 16.8 so we can use hooks if we want

2019-02-12 01:00 UTC, lucleray commented
Additionally to this PR, I think we should, **for each branch of the repo** :
- use prettier (.prettierrc)
- update dependencies

2019-02-13 17:15 UTC, andersonleite commented
@lucleray I updated all the other branches for the newest next and react branches.
About prettierrc, if it's ok for you, I will look at it later.

2021-09-03 02:29 UTC, closed without merging